# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HQvNWJ_MjlHgYoyLhd31AjTWtakROwca
"""

import streamlit as st
import numpy as np
import pandas as pd
import joblib

# === Load model dan komponen preprocessing ===
model = joblib.load("model_svm.pkl")
scaler = joblib.load("scaler.pkl")
label_encoder = joblib.load("label_encoder.pkl")
selected_features = joblib.load("selected_features.pkl")
imputer = joblib.load("knn_imputer.pkl")  # Imputer ditambahkan

# === Setup tampilan halaman ===
st.set_page_config(page_title="Klasifikasi Topik Skripsi", layout="centered")
st.title("🎓 Klasifikasi Topik Skripsi Mahasiswa PTIK")
st.write("Masukkan nilai mahasiswa pada 15 fitur terpilih. Jika ada nilai kosong, biarkan tetap kosong.")

# === Form input fitur ===
input_data = {}
for feature in selected_features:
    val = st.number_input(
        f"{feature}",
        min_value=0.0,
        max_value=100.0,
        value=None,
        format="%.2f",
        step=0.1,
        placeholder="(kosongkan jika tidak tahu)"
    )
    # Gunakan None sebagai indikator missing value
    input_data[feature] = np.nan if val is None else val

# === Prediksi saat tombol ditekan ===
if st.button("🔍 Prediksi Topik Skripsi"):
    input_df = pd.DataFrame([input_data], columns=selected_features)

    # Imputasi nilai kosong dengan KNNImputer
    imputed_input = imputer.transform(input_df)

    # Normalisasi
    scaled_input = scaler.transform(imputed_input)

    # Prediksi
    pred = model.predict(scaled_input)
    label = label_encoder.inverse_transform(pred)[0]

    st.success(f"Hasil prediksi topik skripsi: **{label}** 🎯")